services:
    Acseo\SelectAutocomplete\:
        autowire: true
        autoconfigure: true
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,Events}'

    Acseo\SelectAutocomplete\Doctrine\ManagerRegistry:
        autowire: true
        arguments:
            $registries: '%acseo_select_autocomplete.doctrine_registries%'

    Acseo\SelectAutocomplete\Doctrine\DataProvider\:
        autowire: true
        resource: '../../Doctrine/DataProvider/*'
        tags: ['acseo_select_autocomplete.doctrine.data_provider']
